# Generated by Django 4.1.1 on 2022-09-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=30)),
                ('batafsil', models.TextField(blank=True)),
                ('status', models.CharField(default='Yangi', max_length=12)),
                ('sana', models.DateField()),
            ],
        ),
    ]
