# Generated by Django 4.1.1 on 2022-09-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_remove_plan_foydalanuvchi_student_plan_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
