# Generated by Django 4.1.1 on 2022-10-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_plan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]
